// "Melodies" generated by `midi2c.py` in the `tools` directory.

#ifndef MELODY_H
#define MELODY_H

#include "common.h"

const PROGMEM Tone ALARM_SEQUENCE[] = {
    {1865, 62}, {0, 63},    {1865, 62}, {0, 63}, {1865, 62},
    {0, 63},    {1865, 62}, {0, 563},   {1, 0},
};

const PROGMEM Tone CHARGING_SEQUENCE[] = {
    {523, 124}, {0, 126}, {440, 125}, {349, 125}, {659, 124}, {0, 0},
};

const PROGMEM Tone FACECHANGE_SEQUENCE[] = {
    {415, 62},
    {0, 0},
};

const PROGMEM Tone LOWBATTERY_SEQUENCE[] = {
    {784, 250}, {392, 497}, {0, 253}, {784, 250}, {392, 497}, {0, 0},
};

const PROGMEM Tone NOTCHARGING_SEQUENCE[] = {
    {440, 125},
    {349, 125},
    {330, 124},
    {0, 0},
};

const PROGMEM Tone SHUTDOWN_SEQUENCE[] = {
    {831, 300}, {622, 300}, {415, 300}, {466, 1498}, {0, 0},
};

const PROGMEM Tone STARTUP_SEQUENCE[] = {
    {622, 525}, {311, 75},   {466, 300}, {415, 600},
    {622, 300}, {466, 1198}, {0, 0},
};

#endif